### PR TITLE
Wip sgh new story

### PR DESCRIPTION
**Pull request by sgharms**
I didn't feel like the story we had got across the peril or the "why should I want older versions" (new resume is usually always the best resume). Here's another take. could you review and determine whether it's better?

### CODE REVIEW

**Review by jenmyers — COMMENTED** [review]
I'm split on this one. I get the idea of creating urgency, but I'm worried that beginning with a stressful situation sets a difficult tone and could discourage students. Given that in prework we want to make sure we get students through and to the full course successfully, I feel we might want to err on the side of a less urgent situation.

**Comment by sgharms** [comment]
Cool.  No merge is OK.

**Comment by jenmyers** [comment]
I got Kellye's input on it, however, and she's for the new storyline. That works for me. I'll merge and see if there are any small adjustments to make.

**Comment by sgharms** [comment]
Oh, OK. Well if we merge it then they’re both in the revision history and
we can resurrect as needed. Yay git ;)

**Pull request merged**
